name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hello World Action
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        env:
          MY_NAME: "Usama"
